Реализована задача 238. Реализована задача 239
dr3al/Web_X_backend pull request #4
Opened 2023-03-16 11:32 UTC by Vladick-Pick

Реализована задача 238 - User connection. Реализована задача 239 - Контроллер для получения ID UserConnection

2023-03-17 10:33 UTC, Yitwaaien commented on feature goal/.env
> +MYSQL_USER=vladislav
Файл .env не должен попадать в репозиторий. Он должен быть создан у тебя локально, но ты не должен его пушить в репу. 
Файл .env создается в корне проекта.

2023-03-17 10:34 UTC, Yitwaaien commented on feature goal.zip
Этот файл никак не относится к проекту, его не нужно пушить

2023-03-17 10:35 UTC, Yitwaaien commented on feature goal/config/database.php
Это файл из второго дисциплинарного задания, он никак не относится к проекту. Убери его пожалуйтса

2023-03-17 10:47 UTC, Yitwaaien requested changes
Можно вместо endpoint-a  /user/iduc
объявленого внутри user сделать фильтр в сущности UserConnection, который бы возвращал значение по EXACT поиску принимая user и folower айдишники, могу ошибаться но вроде это 2-6 строчек кода вместо создания контроллера

2023-03-17 10:47 UTC, Yitwaaien commented on feature goal/goal/create.php
не относится к проекту

2023-03-17 10:47 UTC, Yitwaaien commented on feature goal/model/goal.php
не относится к проекту

2023-03-17 10:47 UTC, Yitwaaien commented on src/Controller/UserConnectionController.php
> +    public function findUserConnectionId($user,$follower, EntityManagerInterface $entityManager): ?int
добавь пробел между $user,$folower -> $user, $folower
Добавь типизацию к этим параметрам, какого типа должны быть эти параметры чтобы твой метод однозначо работал

2023-03-17 10:47 UTC, Yitwaaien commented on src/Controller/UserConnectionController.php
> +//     * Метод обрабатывает GET-запрос и возвращает id записи UserConnection, связывающей пользователя и подписчика, по их id.
удали этот большой блок комментариев

2023-03-17 10:47 UTC, Yitwaaien commented on src/Controller/UserConnectionController.php
> +        if (!$userConnection) {
Мы никогда не вовзвращаем null, этого не ожидает увидеть фронтэнд или другое приложение лучше возвращать что то типо: 
return new JsonResponse(['message' => 'связь не найдена'])

2023-03-17 10:47 UTC, Yitwaaien commented on src/Controller/UserConnectionController.php
> +        return $userConnection->getId();
Тот же комментарий что и предыдущий 
 return new JsonResponse(['id' => '$userConnection->getId()'])

2023-03-17 10:47 UTC, Yitwaaien commented on src/Entity/User.php
>      public function __construct()
Консутрктор нужно переставить в начало класса, перед объявлением свойств. Это что-то типо договоренности

2023-03-17 10:47 UTC, Yitwaaien commented on src/Filter/Goal/GoalFilter.php
> +//
весь закоментированый код удалить

2023-03-17 14:30 UTC, Yitwaaien commented on src/Controller/UserConnection/UserConnectionController.php
> +            'user' => $data->getUser()->getId(),
Зачем в этот контроллер передавать всю сущность user? Можно передать просто два айдишника: user, follower - фронтэнд знает эти данные.  
Передавать две болишье сущности не очень хорошо

2023-03-21 11:18 UTC, dr3al approved these changes

2023-03-21 11:18 UTC, merged